#12
gumsu/spring-board pull request #13
Opened 2022-10-15 13:41 UTC by gumsu

## 개요
안녕하세요!
첫 사이드 프로젝트 pr 요청드립니다.
인증 & 인가에 대해서 공부하고 프로젝트에 적용하다 보니 시간이 많이 걸렸습니다...

아직 구현을 못한 부분이 많은데 jwt 토큰 적용 사항에 대해서만 봐주시면 될 것 같습니다.

## 작업사항
- 로그인 시 token 을 발급하도록 하였습니다.
- 인터셉터를 이용해서 user 관련 controller 를 제외한 나머지에 대해 토큰을 확인하게 하였습니다.

## 고민한 부분
- jwt 토큰을 사용하면 이미 발급된 토큰에 대해서는 제어할 수 없어서 로그아웃 부분이 고민입니다.
  - 현재는 그냥 헤더값에 공백을 넣어서 다시 보내는 형식으로 두었는데요. 나중에 redis 에서 블랙리스트 기능 같은 것을 추가하여 해결하는게 좋을까요?
- 토큰 만료 문제 
  - access 토큰 시간을 짧게 하고 refresh 토큰을 사용하려고 합니다. (아래 그림과 같은 방식)
      1. 리프레시 토큰을 어디에 저장하면 좋을까요? 만약 DB에 저장하게 된다면 결국 세션처럼 서버 측에서 user의 상태를 저장해야 하는 건데 이러면 토큰을 쓰는 의미가 없는게 아닌가? 라는 생각이 듭니다.
      
![image](https://user-images.githubusercontent.com/49813916/195989519-f173d7fb-0179-498c-a392-24961bbc01cf.png)

- spring security 사용 안하는 것에 대해서...
  - 처음에 spring security 까지 공부하고 적용하려고 했는데, 이해하고 공부하는게 쉽지 않아서 다 걷어낸 상태입니다.
  - 스프링 시큐리티 없이 인터셉터로만 하는 것에 대해서 어떻게 생각하시는지 궁금합니다.

2022-10-20 19:02 UTC, brainbackdoor requested changes
첫번째 리팩토링 진행하느라 고생하셨어요~ 👍🏻 
첫번째 작업 주제로 인증쪽을 선택하셨군요~ 😬
JWT 토큰을 활용하며 이를 interceptor에 주입하여 인증처리를 하신 부분, 로그아웃 구현한 방식, Controller/Service 테스트를 시도하신 부분 등이 인상적이었어요~
원래 리뷰요청당 피드백을 10개 내로만 남기는걸 선호하는 편인데, 어쩌다보니 좀 많이 남기게되었네요.
혹시 반영하는데 어려움이 있으시다면 메시지 주세요. 
그리고 제 피드백은 반드시 반영해야 하는게 아니라 제 의견을 드리는 것 뿐이므로, 보시고 납득이 안된다면 답글을 달아주셔도 좋고, 반영하지 않으셔도 좋습니다~
그럼 좋은 하루 보내세요~ 🙏🏻

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/config/WebConfig.java
> +            .excludePathPatterns(Arrays.asList("/api/**/user/**"));
- 로그아웃 시에 로그인 여부를 판단하지 않는걸까요?
- 로그인한 유저도 회원가입이 추가로 가능한가요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/controller/PostController.java
> +    public List<PostResponse> getAll(@ModelAttribute PostSearchRequest postSearchRequest) {
getAll, findById
- 값을 가져오는 데에 모두 get을 사용하는건 아니군요. get과 find를 선택하는 나름의 기준이 있을까요?
- [컨벤션](https://github.com/gumsu/challenge-course-side-1/blob/67ec066e1f86ecd3ab4cbc8cb6750b60ac24e4d6/conventions/code-convention.md)에선 메소드를 동사로 사용해야 한다 등의 규칙은 없어보이는데요. 엘레강트 오브젝트 등에서는 조정자의 경우엔 동사를 사용하지만, 객체의 자율성을 보장하기 위해 빌더 등에선 명사를 사용하라고 가이드하는데요. 가령, Car 객체에서 getPosition()을 통해 위치를 가져오라고 하기보다 move() 등의 메소드로 메시지를 보내라고 하죠. 이런 인식에 대해서는 어떻게 생각하시나요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/request/PostCreateRequest.java
> +        if (title.contains("바보")) {
- JSR 303 Bean Validation 의 `@Pattern` 을 활용해보는건 어떨까요
- 기본적인 파라미터 정책 (null, 데이터 형식 등)을 제외한 도메인 모델의 유효성 검증 정책은 객체 생성시 진행하는 것이 정보의 집중, 객체의 책임, 테스트 작성 등에 유리하지 않을까요
- "바보" 등의 정책을 현재 멤버변수로 관리하고 있는데요. 상수로 관리, application.properties에서 관리, 별도의 Entity로 디비에서 관리하는 등 여러가지 방법 중 어떤 것이 적절할까요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/controller/UserController.java
> +    @PostMapping("/signup")
- [컨벤션](https://github.com/gumsu/challenge-course-side-1/blob/67ec066e1f86ecd3ab4cbc8cb6750b60ac24e4d6/conventions/code-convention.md#3-url-%EB%94%94%EC%9E%90%EC%9D%B8) kebab-case를 사용하기로 했어요~

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/controller/UserController.java
> +        return ResponseEntity.ok().headers(httpHeaders).body(HttpStatus.OK);
- 이벤트스토밍에도 남겨뒀었는데요. 비정상 유저라서 강제로 로그아웃을 시켜야 할 경우엔 어떻게 해야 할까요?
- 사용자가 로그아웃을 했지만, 세션하이재킹을 통해 쿠키를 한번 획득하면 서비스를 이용할 수 있겠군요
- 사용자가 로그인하고 여러 탭에서 작업을 하다가 하나의 탭에서 로그아웃하였을 때, 로그아웃을 시도하지 않은 다른 탭에서는 어떻게 동작하나요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/controller/UserController.java
> +        return ResponseEntity.ok().headers(httpHeaders).body(HttpStatus.ACCEPTED);
```suggestion
        String token = userService.signIn(signInRequest);
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.add(JWTTokenProvider.HEADER_STRING, token);
        return ResponseEntity.ok().headers(httpHeaders);
```
- 지역변수는 의미있는 값으로 표기해주는 것이 가독성에 좋습니다.
- ACCEPTED (202)는 제가 알기로 "처리 요청이 수락되었지만, 완료되지 않았다"는 의미로 알고 있어요
- ResponseEntity.ok() 메소드를 사용하면 status로 200을 담아서 보냅니다.

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/auth/JWTTokenProvider.java
> +    public static final String HEADER_STRING = "ACCESS_TOKEN";
키 혹은 정책 등은 applicationl.properties에서 관리하는 건 어떨까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/user/User.java
> +@Table(name = "users")
테이블 명명규칙도 컨벤션 문서에 들어가는건 어떨까요? lowercase이고, 복수형으로 작성하는 건가요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/user/User.java
> +    private LocalDateTime createdAt;
감사정책을 추가하겠다면 JPA Auditing 을 활용해보는건 어떨까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/user/User.java
> +    private Long id;
id, createdAt 등 중복코드들을 어떻게 하면 제거할 수 있을까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/user/User.java
> +    private String email;
이메일 형식에 대해서는 어디서 체크하나요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/user/User.java
> +    private String password;
패스워드 정책은 따로 없나요? 있다면 정책에 대한 책임은 어느 객체가 가져가는게 좋을까요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/user/User.java
> +    private String role;
role은 USER 등 멤버변수로 가지기보다는 enum으로 관리하는 건 어떨까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/interceptor/JWTSignInInterceptor.java
> +        if (headerToken == null || headerToken.equals("") || !jwtTokenProvider.validateToken(headerToken)) {
```suggestion
        if (headerToken == null || headerToken.isBlank() || !jwtTokenProvider.validateToken(headerToken)) {
```

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/auth/JWTTokenProvider.java
> +    public static final String HEADER_STRING = "ACCESS_TOKEN";
HEADER_STRING은 너무 범용적인 용어 아닐까요? HTTP Header에 다른 값들도 추가하게 될 수도 있을텐데요.

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/interceptor/JWTSignInInterceptor.java
> +            throw new RuntimeException("인증 토큰이 유효하지 않습니다.");
- RuntimeException으로 던지면 사용자에게는 어떻게 응답할까요? 현재 구성한 ControllerAdvice를 활용할 수는 없을까요?
- 인증과 관련하여 어떤 응답으로 반환하는게 좋을까요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
Email은 유일한 값이군요~
그렇다면 Entity에서도 이를 보장해주어야 하지 않을까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/request/SignUpRequest.java
> +            .role("USER")
- User 생성시 반드시 "USER" 권한으로만 생성되나요? 이벤트스토밍에 "관리자"라는 개념이 있던데요. 이건 어떻게 생성할 수 있나요?
- dto에서 인가 정책을 부여하는 것보다는 User 객체 생성시 부여하는 것은 어떨까요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/service/UserService.java
> +        User user = userRepository.findByEmail(request.getEmail().toLowerCase())
- 이메일이 반드시 lowercase로 저장되어야 하나요? 그렇다면 이도 User Entity 생성시 변환되어야 하지 않을까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/resources/UserSchma.sql
> +)
- 쿼리문에 대한 형상관리를 위해 flyway를 활용해보는건 어떨까요
- 테이블 명명 규칙이 entity에 명시한 것과 다르군요

2022-10-20 19:02 UTC, brainbackdoor commented on src/test/java/com/example/board/controller/UserControllerTest.java
> +            .build();
자주 사용하는 값은 테스트 픽스쳐를 구성해서 재사용하는 건 어떨까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/test/java/com/example/board/controller/UserControllerTest.java
> +    @DisplayName("/signin 을 요청 시 로그인을 할 수 있다.")
회원가입 정책, 로그인 정책 별 테스트케이스가 필요하지 않을까요
가령 비밀번호가 다를 경우, 어떤 에러가 나오는지, 가입되지 않은 이메일로 로그인을 시도하는 경우 어떤 에러가 발생하는지 등등이요.

2022-10-20 19:02 UTC, brainbackdoor commented on src/test/java/com/example/board/domain/auth/JWTTokenProviderTest.java
> +        assertThat(validateToken).isFalse();
현재는 임의값을 주어 테스트를 진행하셨는데요. (토큰 생성 후  2시간이 지난 후 값을 입력하셨나요?)
Junit 테스트에서만 별도로 EXPIRE_TIME을 아주 작은 값을 주입한 fake 객체를 사용하도록 구성해보시겠어요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/test/java/com/example/board/service/UserServiceTest.java
> +        assertThat(user.getId()).isEqualTo(findUser.getId());
```suggestion
        assertThat(user).isEqualTo(findUser);
```

equauls 를 작성하여 Entity를 직접 비교하는건 어떨까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/test/java/com/example/board/service/UserServiceTest.java
> +        assertThat(user.getId()).isEqualTo(findUser.getId());
```java
// given
Long expected = TEST_USER.getId();
given(userRepository.save(any())).willReturn(TEST_USER);

// when
Long actual = userService.signUp(signUpRequest());

// then
assertThat(expected).isEqualTo(actual);
```
- 테스트 의도를 분명히 드러내느건 어떨까요? 이 테스트는 userService.signUp() 호출 시 실제로 save() 메소드가 정상적으로 동작하여 의도한 응답값을 반환하는지를 확인하고 싶은 것으로 보이는데요. 필요한 부분만 코드로 드러내고 불필요한 부분은 제거하거나 메소드로 추출하는건 어떨까요
- 빌더 페턴을 메소드로 추출하는 것도 좋지만, 값이 필요한거면 상수로 작성해보는건 어떨까요

2022-10-20 19:02 UTC, brainbackdoor commented on src/test/java/com/example/board/service/UserServiceTest.java
> +        given(userRepository.findByEmail(any())).willThrow(IllegalArgumentException.class);
```suggestion

```
- 이 부분은 불필요하지 않을까요?
- 실제로 데이터가 없을 경우에 IllegalArgumentException를 발생시키나요? Optional.empty를 반환하고 service에서 IllegalArgumentException를 발생시키는 것 아닌가요?

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/controller/PostController.java
> +    public List<PostResponse> getAll(@ModelAttribute PostSearchRequest postSearchRequest) {
작성자 정보를 Request 객체로 받고 있네요? 
- 현재 게시글 생성시 로그인 여부를 확인하고 있는데요. 토큰의 유효성만 검증하는 것이 아니라, User 객체를 반환하여 이 메소드로 주입해주려면 어떻게 해야 할까요? HandlerArguementResolver 개념에 대해 학습해보시면 힌트를 얻으실 수 있을거에요

2022-10-20 19:02 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/auth/JWTTokenProvider.java
> +        }
- Checked Exception은 특별한 경우에만 사용합니다. 기본은 RuntimeException을 사용해주시면 됩니다. 이 경우엔, JwtException과 IllegalArguementException을 체이닝하여 해결할 수 있어요
- Exception을 흘려보내고 있는 것 역시 안티 패턴으로 알고 있어요 


> https://www.slipp.net/questions/350
> https://madplay.github.io/post/effectivejava-chapter10-exceptions

2022-10-20 19:02 UTC, brainbackdoor commented on src/test/java/com/example/board/service/UserServiceTest.java
> +    @DisplayName("회원가입을 할 수 있다.")
현재 Controller 테스트, Service 테스트 등 Mock을 이용한 슬라이스 테스트만 존재하는데요. 저는 슬라이스 테스트는 작성하지 않더라도, 전체를 관통하는 인수 테스트는 작성해야 한다고 생각해요

2022-10-20 19:19 UTC, brainbackdoor commented
질문하신 부분에 대해 답글을 작성하지 않았네요
- 발급한 토큰은 말씀하신것처럼 redis 혹은 ehcache 등을 활용하셔도 좋고, MySQL 에서 관리하셔도 괜찮습니다. (DB에서 관리하는 것이 IO가 발생해서 비효율적이라고 생각할 수 있지만, 현 시점에선 그부분에 대해 문제라고 느낄 지점이 아니라고 생각합니다.)
- access token을 저장하여 매 요청마다 디비에서 확인하는 것보다, 만료기한이 지났을 떄, refresh token을 활용하여 확인하는 것이 IO가 적게 듦으로 유리하여 사용하는 방식입니다. 애초에 access token의 만료기한을 짧게 설정하는 이유는 access token은 보안상 취약합니다. 브라우저에서 관리하므로 탈취될 가능성이 높기 떄문이죠. 보안성을 높이면서 토큰의 이점을 활용하기 위한 차선책이라고 생각해주시면 될 듯합니다. 
- Spring, Spring Data Access, Spring Security 이런 것들은 어떻게 생겨났을까요? 엔터프라이즈급에서 공통적으로 작업하던 것들이 추상화되면 만들어진 것인데요. 그러다보니 사용하지 않는 기능들도 참 많아요. 그래서 추상화 수준이 높을수록 처음 사용할 때 러닝커브가 높은거 같아요. 당연히 사용하지 않고 직접 필요한 기능만 구현하여 사용해도 좋습니다. (우테코에서도 Spring Security는 사용하지 말도록 가이드하고 있어요. 그 이유는 미리 학습을 해왔던 게 아니라면 프로젝트 할 때 인증/인가 쪽이 늘 병목지점이 되더라구요.)

2022-10-25 11:58 UTC, gumsu commented on src/main/java/com/example/board/domain/auth/JWTTokenProvider.java
> +    public static final String HEADER_STRING = "ACCESS_TOKEN";
키와 정책을 속성파일로 옮기다보니, 기존 순수 자바 테스트 -> 스프링 통합 테스트로 변경되었는데 이 부분은 어쩔 수 없는 걸까요?

2022-10-25 12:01 UTC, gumsu commented on src/test/java/com/example/board/domain/auth/JWTTokenProviderTest.java
> +        assertThat(validateToken).isFalse();
토큰 생성 2시간 이후의 값을 가져와서 테스트한게 맞습니다 😅
EXPIRE_TIME 를 임의로 변경하기 위해 부득이하게 리플렉션을 사용했는데, 혹시 다른 방법이 있는지 궁금합니다..!

2022-10-25 12:04 UTC, gumsu commented on src/main/java/com/example/board/interceptor/JWTSignInInterceptor.java
> +            throw new RuntimeException("인증 토큰이 유효하지 않습니다.");
ControllerAdvice 에서 받을 수 있도록 변경하였습니다. 👍
기존에 만들어둔 ErrorResponse 에 담아서 반환하도록 추가하였습니다!

2022-10-25 12:06 UTC, gumsu commented
동규님 꼼꼼한 리뷰 감사합니다. 😊
이번 PR 에서는 JWT 토큰에 관련한 사항만 수정해보았습니다.
나머지 리뷰 주신 사항들은 추후 다른 이슈에서 수정하여 적용하겠습니다!

감사합니다. 🙇‍♀️

2022-10-26 14:22 UTC, brainbackdoor approved these changes
넵~ 피드백 반영 확인했어요
작업 단위로 커밋을 나눠 진행하신 부분 인상적이었어요~ 👍🏻 
다음 리팩토링 작업도 파이팅입니다~ 🙌🏻

2022-10-26 14:22 UTC, brainbackdoor commented on src/main/java/com/example/board/controller/UserController.java
> +        return ResponseEntity.ok().headers(httpHeaders).body(HttpStatus.OK);
```suggestion
        return ResponseEntity.ok().headers(httpHeaders);
```
이렇게 반환해도 같지 않나요?

2022-10-26 14:22 UTC, brainbackdoor commented on src/main/java/com/example/board/domain/auth/JWTTokenProvider.java
> +            throw new InvalidToken();
👍🏻

2022-10-26 14:22 UTC, brainbackdoor commented on src/main/java/com/example/board/interceptor/JWTSignInInterceptor.java
> +    private final JWTTokenProvider jwtTokenProvider;
👍🏻

2022-10-27 08:12 UTC, merged